### ISSUE TITLE
i have seen one for beluga too, do these portals exist for cedar and graham too?

### ISSUE THREAD

**Issue by ucalyptus2** [guilbaults/TrailblazingTurtle#12]
Great code @guilbaults

**Comment by guilbaults** [comment]
Graham is still using a very old version of the portal, we are currently upgrading the monitoring stack on the cluster to update the portal to the latest version:
https://dashboard.graham.sharcnet.ca/
This upgrade will be completed hopefully in the next 4 weeks

Cedar does not currently gather the required stats due to a lack of sysadmin time to install the requirements

At the moment, the development is done on Beluga and Narval:
https://portail.narval.calculquebec.ca/
https://portail.beluga.calculquebec.ca/

**Comment by guilbaults** [comment]
Hi, please open a ticket with support@tech.alliancecan.ca, this is a problem with the IDP (Shibboleth). Based on the email/username, we will be able to check the logs to see what error you are having.

**Comment by netscruff** [comment]
@forkbabu you don't need to open a ticket, this is expected and once I've been told the portals are ready for general use, they will allow access.
